const productos = [{
        id: 1,
        nombre: "Teclado gamer HyperX Alloy Origins",
        precio: 13500,
        descripcion: "El HyperX Alloy Origins™ Core es un teclado tenkeyless ultra compacto y robusto que cuenta con interruptores mecánicos diseñados para brindarles a los gamers la mejor combinación de estilo, rendimiento y confiabilidad.",
        img: "./assets/img/card1.jpg",
        descuento: "Paga un 21% en un solo pago o solo un 30% mas en 6 cuotas sin interes",
        cantidad: 1,
    },
    {
        id: 2,
        nombre: "Monitor 25 Pulgadas Benq Zowie Xl2546k 240hz",
        precio: 182359,
        descripcion: "Disfrutá de todas las cualidades que el monitor BenQ XL2546K tiene para ofrecerte. Percibí las imágenes de una manera completamente diferente y complementá cualquier espacio ya sea en tu casa u oficina.",
        img: "./assets/img/card2.jpg",
        descuento: "Descuentos con Lemoncard",
        cantidad: 1,
    },
    {
        id: 3,
        nombre: "MICROPROCESADOR INTEL CORE I5 10600K 4.8GHZ",
        precio: 52700,
        descripcion: "Productividad y entretenimiento, todo disponible en tu computadora de escritorio. La superioridad tecnológica de INTEL es un beneficio para todo tipo de profesionales. Asegura el mejor rendimiento de las aplicaciones, de la transferencia de datos y la conexión con otros elementos tecnológicos.",
        img: "./assets/img/card3.jpg",
        descuento: "Descuentos con Santander Rio y SmartBank",
        cantidad: 1,
    },
    {
        id: 4,
        nombre: "Placa de video 8GB RTX 3070 TI ASUS TUF GAMING O8G",
        precio: 231680,
        descripcion: "Calidad de imagen. Criterio fundamental a la hora de elegir una placa de video, su resolución de 7680x4320 no te defraudará. La decodificación de los píxeles en tu pantalla te harán ver hasta los detalles más ínfimos en cada ilustración.",
        img: "./assets/img/card4.jpg",
        descuento: "No hay descuentos disponibles para este producto",
        cantidad: 1,
    },
];